### ISSUE TITLE
Configure Dashboards by projects

### ISSUE THREAD

**Issue by mburamorde** [initOS/MantisBT-Dashboard#1]
Hallo,

ist es möglich Dashboards je nach Projekt zu konfigurieren? Wenn nicht: Wo müsste man ansetzen? 

Gruß,
Michael 

Is it possible to configure Dashboards by projects? If not: where could one start?

**Comment by paulgoetze** [comment]
I edited the comment and title to English just not to suspend other contributors.

To your question: Do you mean, you want to be able to switch the set of custom boxes for different projects? Then this is not implemented yet. So far only the boxes projects adjust when choosing another project from the projects dropdown. 

To implement this, I think the best way is to modify the [`get_positioned_custom_boxes_data`](../blob/cd7bbcba47723815c05edb317fd5348028e0ca27/Dashboard/api/dashboard_db_api.php#L552-599) function to return the boxes for the appropriate Dashboard. This function is used to fetch and return the custom boxes data which is passed to the print API to calculate the boxes html. 
To save and load different positioned boxes it might be a good idea to add a `project_id` column to the `custom_boxes` table and the needed reference in the `custom_boxes_positions` table (this goes with several updates in the load and save functionality).

I hope this will help a bit. Contributions are greatly welcome!

**Comment by mburamorde** [comment]
Hello,

I created an pull request for your project! Please check it an accept is, if possible.

Thanks,
Michael

**Comment by paulgoetze** [comment]
Configurable by projects Dashboard is now available after some additional fixes through #3.

Thanks again @mmmichael, great work!
