### ISSUE TITLE
Set amount of shown tickets individually per box

### ISSUE THREAD

**Issue by choeft** [initOS/MantisBT-Dashboard#6]
Hi guys,

great plugin, I only have been using it for a few hours and it helps me a lot! 

One questions: would it be possible to implement another input field which lets me decide how many tickets/bugs I want to see in each box?

As I understand it, the default is 10, but for some filters I don't want to see that many tickets/bugs.

It seems the boxes ignore the amount that has been set in the filter...

Thank you,
Constantin

**Comment by paulgoetze** [comment]
Hi Constantin, good point! I will look at it within the next days.

**Comment by paulgoetze** [comment]
This feature is available since [v0.7.0](../releases/tag/v0.7.0) (31cc38619d2314c39ab4a261719eda80a710c88d).
